### ISSUE TITLE
EPIC: `local-ic` misc issue tracking ticket

### ISSUE THREAD

**Issue by Reecepbcups** [strangelove-ventures/interchaintest#795]
```[tasklist]
### Tasks
- [x] make install for go releaser instead of go install ./... so version is set https://github.com/strangelove-ventures/interchaintest/pull/1149
- [ ] [Mainnet interaction across networks](https://github.com/strangelove-ventures/interchaintest/pull/291) (cosmos dir RPCs),
- [x] Drivers: Bash (get/post examples, then allow curl down + [source from url](https://superuser.com/questions/255260/bash-source-from-url)) https://github.com/strangelove-ventures/interchaintest/pull/1207
- [ ] More IBC Abilities (Ex: ICA, Mesh Security, Polytone). Pending https://github.com/strangelove-ventures/interchaintest/issues/1094
- [ ] Support upgrades _(spawn a new fullnode & wait on that, not the validator else panic)_
- [ ] Allow mounting (ref main Ethereum chain start)
- [ ] Auto set keyring-backend=test for local-ic config
- [ ] pipe logs to a file, don't block on the end. On exit print out where (pipe logs to a file, don't block on the end. On exit print out where). Stream tailed logs from the container (docker logs -f -n 100 or something?)
- [x] on ctrl+c remove all running containers https://github.com/strangelove-ventures/interchaintest/pull/1206
- [x] Easy CW upload & init from within interaction
- [ ] Fix multiple tokens spreading out over many commands (some networks like osmosis do not have --append support)
- [ ] How to launch testnets (public & private). [ref spawn for CI](https://github.com/rollchains/spawn/blob/release/v0.50/simapp/.github/workflows/testnet-hetzner.yml)
- [ ] More docs on interaction (req by Steve & Ollie @ ICF)
- [ ] Polkachu snapshots -> mainnet with v50 in place testnets
- [ ] Add service file which we did for ethos for running
- [x] Docker compose support (running alongside), and sidecars
- [ ] https://github.com/strangelove-ventures/interchaintest/issues/1182
- [ ] [Kubernetes / Gitlab CI integration](https://github.com/strangelove-ventures/interchaintest/issues/1075#issuecomment-2284314398) (Done, just need to write docs / verify)
- [ ] use as bases possible https://github.com/strangelove-ventures/interchaintest/pull/1219#discussion_r1725972315
- [ ] add thorchain / utxo chain support
- [ ] add some examples to write test in other languages at the top level folder, so the readme points to local-ic - [request](https://x.com/GjermundGaraba/status/1829109823629115578)
```

**Comment by Reecepbcups** [comment]
This is ugly, add a local-ic helper

```
curl -X POST -H "Content-Type: application/json" -d '{
  "chain_id": "localcosmos-1",
  "action": "query",
  "cmd": "bank balances cosmos1hj5fveer5cjtn4wd6wstzugjfdxzl0xpxvjjvr"
}' http://127.0.0.1:8080/
```

`local-ic interact localcosmos-1 query bank balances cosmos1hj5fveer5cjtn4wd6wstzugjfdxzl0xpxvjjvr` would build this out
