### ISSUE TITLE
EPIC: Template test should have explanations

### ISSUE THREAD

**Issue by Reecepbcups** [strangelove-ventures/interchaintest#882]
(per Sendar on current docs) and also for Spawn

- [ ] have a very basic test and each step is explained.
- [ ] create testing templates people can build on top of easily
- [ ] Link to Relayer test for IBC help 

examples:
- contract testing template
- module testing template
- ibc module testing template
- Many chains testing template (like PFM)
- hyperspace testing template?
- Advanced testing templates (with sidecar processes and stuff like neutron icq)?

**Comment by jonathanpberger** [comment]
This work is gonna be done on the Rollchains side (until the come back and upstream things). Unstarting ticket for now.

**Comment by Reecepbcups** [comment]
moving template test out of scope for now. Better documentation should take precedence over this. Working through what that looks like, but templates are not it atm. (scopes for test are too broad, having many examples is close enough to templates while doing something actually useful)
